### ISSUE TITLE
torch_main中for batch_id, (X1, X2, X3, m1, m2, m3) in enumerate(trainLoader, 1):

### ISSUE THREAD

**Issue by ReUsea** [DeepSoftwareAnalytics/LibDB#1]
您好，
在torch_main中for batch_id, (X1, X2, X3, m1, m2, m3) in enumerate(trainLoader, 1)中该句话代码报错：
  File "/home/yanghaiyun/anaconda3/envs/tpldetection/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 67, in __iter__
    return iter(range(len(self.data_source)))
TypeError: 'float' object cannot be interpreted as an integer
可以指教一下这个问题吗？

**Comment by lkpsg** [comment]
train data 成功生成了吗？

**Comment by lkpsg** [comment]
建议先检查一下train data是否成功生成。

**Comment by Slarkzzz** [comment]
您好，我已经生成train data。后来修改了下dataset.py中len函数的返回值类型，可以正常训练了。

**Comment by ReUsea** [comment]
您好，我已经生成train data。后来修改了下dataset.py中len函数的返回值类型，可以正常训练了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Wei ***@***.***>
发送时间: 2022年10月3日 23:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [DeepSoftwareAnalytics/LibDB] torch_main中for batch_id, (X1, X2, X3, m1, m2, m3) in enumerate(trainLoader, 1): (Issue #1)


建议先检查一下train data是否成功生成。

―

**Comment by JiachengSong** [comment]
> 您好，我已经生成了训练数据。其实修改了下dataset.py中len函数的返回值类型，就可以正常训练了。来自Windows版邮件< [https://go.microsoft.com/fwlink/?LinkId=550986 > 发送](https://go.microsoft.com/fwlink/?LinkId=550986>%E5%8F%91%E9%80%81) 发件人： 魏***@***.***> 发送时间： 2022年10月3日 23:25 食谱： ***@***.***> 抄送： ***@***.***>； ***@***.***> 主题: Re: [DeepSoftwareAnalytics/LibDB] torch_main中for batch_id, (X1, X2, X3, m1, m2, m3) in enumerate(trainLoader, 1): (问题[# 1](https://github.com/DeepSoftwareAnalytics/LibDB/issues/1) ) 建议先检查一下训练数据是否成功生成。 ― 直接回复此邮件，在 GitHub 上查看< [https://nam12.safelinks.protection.outlook.com/ ?url=https%3A%2F%2Fgithub.com%2FDeepSoftwareAnalytics%2FLibDB%2Fissues%2F1%23issuecomment-1265638563&data=05%7C01%7C%7Cbd4858e753714e7bb51008daa55384d5%7C84df9e7fe9f640af b4 35aaaaaaaaaaaa%7C1%7C0%7C638004075385372566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000% 7C%7C%7C&sdata=YLmUAKByYGqaanRQVrTHKy362BMyU%2FRH64TE0pMYMRs%3D&reserved=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDeepSoftwareAnalytics%2FLibDB%2Fissues%2F1%23issuecomment-1265638563&data=05%7C01%7C%7Cbd4858e753714e7bb51008daa55384d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638004075385372566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YLmUAKByYGqaanRQVrTHKy362BMyU%2FRH64TE0pMYMRs%3D&reserved=0) >，或取消订阅< [https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe- auth%2FATUSB3BOWAECKI7HHRMSR53WBL3G5ANCNFSM6AAAAAAQYOPIG4&data=05%7C01%7C%7Cbd4858e753714e7bb51008daa55384d5%7C84df9e7f e9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638004075385372566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qgt2SkWF7NlP5Pu4kWHO7I%2BjZorZqGAiAyCq4ITbtAM%3D&reserved=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATUSB3BOWAECKI7HHRMSR53WBL3G5ANCNFSM6AAAAAAQYOPIG4&data=05%7C01%7C%7Cbd4858e753714e7bb51008daa55384d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638004075385372566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qgt2SkWF7NlP5Pu4kWHO7I%2BjZorZqGAiAyCq4ITbtAM%3D&reserved=0) >。您收到此消息是因为您是该帖子的作者。消息ID：***@** *.***>

你好，请问您是如何修改dataset.py中len函数的返回值类型的
