### ISSUE TITLE
FedoraLib_Dataset.7z  cannot be extracted

### ISSUE THREAD

**Issue by qinzhengze** [DeepSoftwareAnalytics/LibDB#2]
FedoraLib_Dataset.7z  cannot be extracted in Windows10， Prompt that the compressed file is damaged！

**Comment by lkpsg** [comment]
I have tried it on Linux using 7z, it succeeded to decompress everything. 
download all archives and run the command "7z x FedoraLib_Dataset.7z.001". it would extract all 5 .7z files.
