### ISSUE TITLE
Problems in detection:

### ISSUE THREAD

**Issue by zzzghttt** [DeepSoftwareAnalytics/LibDB#3]
您好，请问您在论文中提到的Basic Feature Matching过程是在哪段代码中，包括在function_vector_channel.py的结果中了吗？
另外，请问base_afcg.py和b2sfinder_afcg.py中21行用到的base_result：
parser.add_argument('--base_result', type=str, default='../data/detection/base/base_result_b2sfinder_rule.json',
                    help='result of base matching method')
parser.add_argument('--base_result', type=str, default='../data/detection/b2sfinder/b2sfinder_results.json',
                    help='result of base matching method')

是baseline生成的吗？源码中好像没有给出。

**Comment by lkpsg** [comment]
基础特征生成的结果是直接使用[b2sfinder](https://github.com/1dayto0day/B2SFinder)的规则和代码生成的。详情可查阅原代码仓库。

**Comment by JiachengSong** [comment]
> 您好，请问您在论文中提到的Basic Feature Matching过程是在哪段代码中，包括在function_vector_channel.py的结果中了吗？ 另外，请问base_afcg.py和b2sfinder_afcg.py中21行用到的base_result： parser.add_argument('--base_result', type=str, default='../data/detection/base/base_result_b2sfinder_rule.json', help='result of base matching method') parser.add_argument('--base_result', type=str, default='../data/detection/b2sfinder/b2sfinder_results.json', help='result of base matching method')
> 
> 是baseline生成的吗？源码中好像没有给出。

您好，请问您在复现这些工作时，id2package.json这个文件我无法找到从哪里获得
